apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.example.com
spec:
  group: example.com
  names:
    kind: Website
    listKind: WebsiteList
    plural: websites
    singular: website
    shortNames:
    - ws
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              domain:
                type: string
                description: "The domain name for the website"
              replicas:
                type: integer
                description: "Number of replicas to run"
                minimum: 1
              image:
                type: string
                description: "Container image to use"
              port:
                type: integer
                description: "Port to expose"
                minimum: 1
                maximum: 65535
    subresources:
      status: {} 