apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubernetes resources to be managed by kustomize
resources:
- nginx-deployment.yaml
- nginx-service.yaml

# Customizations that need to be made
labels:
- includeSelectors: true
  pairs:
    environment: production
